# Generated by Django 4.2.7 on 2023-11-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_regiao_macro_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='macro_regiao',
            field=models.CharField(choices=[('AMERICA_SUL', 'América do Sul'), ('AMERICA_NORTE', 'América do Norte'), ('AMERICA_CENTRAL', 'América Central'), ('ASIA', 'Ásia'), ('AFRICA', 'África'), ('ARABIA', 'Arábia '), ('OUTROS', 'Outros')], default='OUTROS', max_length=30),
        ),
    ]
